version: '3'

services:
  postgresql:
    container_name: postgresql
    image: postgres:11.7-alpine
    environment:
      POSTGRES_DB: "klios"
      POSTGRES_USER: "default"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data 
    networks:
      - postgres-network
      
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "jo4o.fds@gmail.com"r
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - postgresql
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
