version: '3'

services:
  klios-postgres-compose:
    image: postgres:11.7-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - /home/joaofds/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  klios-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "jo4o.fds@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - klios-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge